### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by khinsen** [SquareBracketAssociates/Booklet-DataFrame#3]
The booklet is seriously out of date. Many functions have been removed, and as a consequence many examples no longer work. Examples of no-longer-existing methods are
 - fromCSV
 - loadIris.
 - select:where:

**Comment by Ducasse** [comment]
Yes. Oleksandr will do a pass on it and release a new version. This is planned.

**Comment by olekscode** [comment]
Hello, @khinsen 
Thank you for creating this issue. I have indeed made major updates to DataFrame but didn't update the booklet yet. I will do it as soon as possible (as soon as I cure my flu and feel a bit better) and release the new version of DataFrame together with the updated booklet.

**Comment by khinsen** [comment]
Great, thanks!

**Comment by olekscode** [comment]
Booklet is now up to date with the current version of DataFrame

**Comment by khinsen** [comment]
Looks good - thanks!
